// <auto-generated />
using System;
using EFCoreCodeFirstSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreCodeFirstSample.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20190214120921_addedTwo")]
    partial class addedTwo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreCodeFirstSample.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1L,
                            DateOfBirth = new DateTime(2015, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mbernasek0@cargocollective.com",
                            FirstName = "Mabelle",
                            LastName = "Bernasek",
                            PhoneNumber = "953-382-3399"
                        },
                        new
                        {
                            EmployeeId = 2L,
                            DateOfBirth = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cartindale1@archive.org",
                            FirstName = "Chrotoem",
                            LastName = "Artindale",
                            PhoneNumber = "615-262-3124"
                        },
                        new
                        {
                            EmployeeId = 3L,
                            DateOfBirth = new DateTime(2018, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gseabrook2@homestead.com",
                            FirstName = "Gertrud",
                            LastName = "Seabrook",
                            PhoneNumber = "607-614-8672"
                        },
                        new
                        {
                            EmployeeId = 4L,
                            DateOfBirth = new DateTime(1111, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofija@sofija.com",
                            FirstName = "Sofija",
                            LastName = "Vlahovic",
                            PhoneNumber = "666-666-6666"
                        },
                        new
                        {
                            EmployeeId = 5L,
                            DateOfBirth = new DateTime(1111, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sofija@sofija.com",
                            FirstName = "Sofija",
                            LastName = "Vlahovic",
                            PhoneNumber = "666-666-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
